Make compatible with EIP 1193, EIP 1102, and permissions system
MetaMask/providers pull request #11
Opened 2019-11-14 00:51 UTC by rekmarks

This makes the inpage provider compatible with EIP 1193, EIP 1102, and EIP 2255 (i.e., [this branch of the extension](https://github.com/MetaMask/metamask-extension/tree/LoginPerSite)). It also sets us up for the December 16 API changes (basically, delete everything marked with `TODO:deprecate:2019-12-16`).

Some noteworthy changes:
- metadata handling moved from extension to here
- `ethereum._metamask` proxy moved from extension to here
- `ethereum.send` fully implemented per EIP 1193
- major version bump to `4.0.0`
  - changes are breaking if the background does not use EIP 2255

We probably shouldn't merge this and publish the package until the extension's `LoginPerSite` PR is approved, but we definitely review it now.

2019-11-14 05:17 UTC, danfinlay approved these changes
Looks good! A few things you might want to tighten up or discuss, but I don’t see anything worth blocking. Very clean, pleasant to read!

2019-11-14 05:17 UTC, danfinlay commented on index.js
> +      this.emit('chainChanged', this.chainId)
Does this work with our current network controller? Last time I was trying to do this, it needed some refactoring.

2019-11-14 05:17 UTC, danfinlay commented on index.js
> -  // drizzle accidently breaking the `this` reference
Does drizzle still work after this change? If not, have we notified them of it?

2019-11-14 05:17 UTC, danfinlay commented on index.js
> +    // wrap params in array out of kindness
Pro tip acquired

2019-11-14 05:17 UTC, danfinlay commented on index.js
> +MetamaskInpageProvider.prototype._requestAccounts = function () {
Maybe could have been a little cleaner as an async method.

Also why using internal sendAsync instead of regular send here?

2019-11-14 05:17 UTC, danfinlay commented on index.js
> +      console.warn(messages.warnings.signTypedDataDeprecation)
Maybe this is just me, but if we aren’t planning to remove it or change how it works, why clutter the logs with it? A few warnings here I think we could just drop, or maybe reduce to info.

2019-11-14 05:17 UTC, danfinlay commented on index.js
> +  if (window.web3) {
Might want to also check for window.web3.eth, for ultimate safety.

2019-11-14 16:58 UTC, rekmarks commented on index.js
> +      this.emit('chainChanged', this.chainId)
Yes, I confirmed that chainId is on the inpage provider, and that the event works (although it only has the wrong name in production).

2019-11-14 17:00 UTC, rekmarks commented on index.js
> -  // drizzle accidently breaking the `this` reference
I assume so, since we closed that issue (https://github.com/metamask/metamask-extension/issues/5459) after Truffle/Drizzle said it should be fine.

2019-11-14 17:04 UTC, rekmarks commented on index.js
> +  if (window.web3) {
Done

2019-11-14 19:29 UTC, rekmarks commented on index.js
> +MetamaskInpageProvider.prototype._requestAccounts = function () {
`_sendAsync` does some preflight checks/preprocessing before handing requests off to `rpcEngine.handle`.

I ended up moving this method to an async middleware in the extension background, where it should live.

2019-11-14 19:45 UTC, rekmarks commented on index.js
> +      console.warn(messages.warnings.signTypedDataDeprecation)
Upon review, I removed the warning for that method completely. The rest are either being removed or things that I hope to remove.

2019-11-15 14:47 UTC, Gudahtt commented
It looks like this needs to be rebased; there are conflicts.

2019-11-15 15:00 UTC, rekmarks commented
@Gudahtt fixed!

2019-11-21 15:55 UTC, Gudahtt reviewed
Here's the first part of my review - I'm still only part-way through.

2019-11-21 15:55 UTC, Gudahtt commented on .nvmrc
> +v10.16.0
Nit: We _just_ updated to v10.17.0 in the `metamask-extension` repo. Maybe worth using here as well.

2019-11-21 15:55 UTC, Gudahtt commented on index.js
> +    // TODO:deprecate:2019-12-16
I guess this date could be updated 👀

2019-11-21 15:55 UTC, Gudahtt commented on index.js
> +const _state = {
Could this state be moved onto the `MetamaskInpageProvider` instance? The fact that it's in module scope effectively makes `MetamaskInpageProvider` into a singleton.

2019-11-21 15:55 UTC, Gudahtt commented on index.js
> +        return Array.isArray(_state.accounts) && _state.accounts.length > 0
Huh. Nothing async going on here, as it's not waiting for the first state update from the background anymore.

Technically this is a breaking change, as this will now return false negatives just like `isEnabled` does. I'm not sure how much I _care_ that it's a breaking change, as it's experimental and due for removal, but... this does kinda make this method useless.

2019-11-21 15:55 UTC, Gudahtt commented on index.js
> +        return _state.isUnlocked
Same case as for `isApproved` - I think this'll fail if called early enough, in the same manner as `isEnabled`

2019-11-21 15:55 UTC, Gudahtt commented on index.js
> +        return Array.isArray(_state.accounts) && _state.accounts.length > 0
We could probably wait for the first call of `_handleAccountsChanged`, and then the behavior would be the same 🤔

2019-11-21 15:55 UTC, Gudahtt commented on index.js
> +function getExperimentalApi (instance) {
I've added a `registerOnboarding` experimental method in the `one-click-onboarding` branch that'll need to be ported over here I suppose 🤔 

I'll consider this further - maybe we can stash that somewhere else. It feels a little inappropriate to go here.

2019-11-21 16:36 UTC, rekmarks commented on index.js
> +        return Array.isArray(_state.accounts) && _state.accounts.length > 0
Yeah, I don't think it's a big deal either, but we shouldn't break it. It now waits for the first emission of `accountsChanged`.

2019-11-21 16:36 UTC, rekmarks commented on index.js
> +        return _state.isUnlocked
Now waits for first `_publicConfigStore` update.

2019-11-21 16:42 UTC, rekmarks commented on index.js
> +function getExperimentalApi (instance) {
Hm, yeah that's more of a caper. Would we need to set up the `onboardingStream` in the inpage provider for that to work? If not, I think it is ultimately fine if it lives here.

On the other hand, there is perhaps a case to be made for experimental methods closely tied to the background to be defined in the background in `inpage.js`? Although, in the end, everything still "lives" in the same place at runtime?

2019-11-21 21:58 UTC, Gudahtt requested changes

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> +function getExperimentalApi (instance) {
This should probably be a method I guess? Otherwise the `this` references will refer to this function, not the provider instance.

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> +  // chainChanged and networkChanged events
Nit: this function also handles reacting to the wallet locking/unlocking

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> +        params,
Nit: `params` can be omitted here, since it's undefined.

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> +      payload.method === 'eth_accounts' ||
It seems a bit weird to me that a read-only method would have a side-effect 🤔 

Are there existing cases where the accounts can change without the provider knowing?

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> -    if ('selectedAddress' in state && state.selectedAddress !== self.selectedAddress) {
Hmm. So changes to `selectedAddress` are no longer transmitted via this stream. How is this now being communicated to the provider?

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> +      sentWarnings: {
Nit: indentation is off here

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> +    logStreamDisconnectWarning.bind(this, 'MetaMask PublicConfigStore'),
Interesting 🤔 This does severely hamper the abilities of the provider though - it can't fulfill it's duties anymore in sending events like `chainChanged`.

Maybe this is fine. I'm not sure that emitting `close` would be better. It does seem unsatisfying though.

Ah well - it matches the previous behavior at least, so I have no objections.

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> +  // EIP-1193 subscriptions
I don't see a reference to a `data` event in EIP-1193 - perhaps I'm missing something?

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> +    if (!Array.isArray(params)) {
This seems to be a breaking change. Previously `.send`'s second parameter was a callback. Anybody now passing a callback to `.send` will find that it's wrapped in an array and treated as a set of parameters.

2019-11-21 21:58 UTC, Gudahtt commented on index.js
> +    // we will throw further down if it isn't
Similarly, this will break any dapps passing a request object and a callback to `.send`

2019-11-21 22:38 UTC, rekmarks commented on index.js
> +function getExperimentalApi (instance) {
Ah, I missed updating the `_state` references to `instance._state` after making `_state` into an property of `MetamaskInpageProvider`. The reason this function isn't a class method is that I was having trouble with the `this` binding of the `Proxy`.

2019-11-21 23:12 UTC, rekmarks commented on index.js
> -    if ('selectedAddress' in state && state.selectedAddress !== self.selectedAddress) {
Due to `LoginPerSite`, the preference controllers `selectedAddress` is no longer of relevance to external domains. Whatever accounts we get from the permissions controller via `eth_accounts` and JSON RPC notifications are what we care about.

2019-11-21 23:15 UTC, Gudahtt commented on index.js
> +function getExperimentalApi (instance) {
Hey whatever works is fine by me. That was just a suggestion for how to fix it, I hadn't thought about the implications of it being within a proxy.

2019-11-21 23:16 UTC, rekmarks commented on index.js
> +    logStreamDisconnectWarning.bind(this, 'MetaMask PublicConfigStore'),
Hm, I'm not following. Those lines - which relate to the `publicConfig` stream - work exactly the same now as they did before. In testing, `chainChanged` and `networkChanged` are emitted as expected. Are you referring to something else?

2019-11-21 23:18 UTC, Gudahtt commented on index.js
> +    logStreamDisconnectWarning.bind(this, 'MetaMask PublicConfigStore'),
I mean that the `publicConfig` stream is being treated here as a non-critical, even though it'd mean that the provider would only be half-working if it failed.

2019-11-21 23:22 UTC, Gudahtt commented on index.js
> +    logStreamDisconnectWarning.bind(this, 'MetaMask PublicConfigStore'),
To be more specific: `_handleDisconnect` isn't being called here in the event of failure.

I'm not totally sure how this worked before 🤔. I see that there's a similar method called `_onClose` in `createStandardProvider`, but I don't see it being called anywhere...

2019-11-21 23:23 UTC, rekmarks commented on index.js
> +  // EIP-1193 subscriptions
Hm, strange. This was originally there, and we basically emitted a `data` event that we created a listener for which then emitted a `notification` event. I changed this to just emit a `notification` event.

2019-11-21 23:23 UTC, rekmarks commented on index.js
> +    if (!Array.isArray(params)) {
Good catch, fixing that.

2019-11-21 23:25 UTC, rekmarks commented on index.js
> +      payload.method === 'eth_accounts' ||
I'm pondering that. I may just have done it as a defensive measure. TBD...

2019-11-21 23:31 UTC, Gudahtt commented on index.js
> -    if ('selectedAddress' in state && state.selectedAddress !== self.selectedAddress) {
Right, of course, sorry I misrepresented myself there. What I should have asked is: how is the provider notified when the user switches accounts?

Also, the act of switching accounts was also how the provider used to be notified of _new_ accounts being created, because upon creating a new account you'd also switch to it. Is the provider still notified when a new account has been created?

This relates somewhat to this comment: https://github.com/MetaMask/metamask-inpage-provider/pull/11#discussion_r349292382

I don't think the old provider handled this particularly well either, as I'm pretty sure you could remove accounts without the provider being notified until you happened to switch accounts as well.

2019-11-21 23:32 UTC, rekmarks commented on index.js
> +    logStreamDisconnectWarning.bind(this, 'MetaMask PublicConfigStore'),
Thinking about this one, I don't know if there's a case where a single stream fails; I think they all go or none of them do, and I've never seen any evidence to the contrary. That said, my reasoning here was that, even if the `publicConfig`-related functionality breaks, you can still send RPC requests. If we interpret `connect` and `close` as related to Ethereum network connectivity, should we continue to not emit `close`?

2019-11-21 23:34 UTC, Gudahtt commented on index.js
> +    logStreamDisconnectWarning.bind(this, 'MetaMask PublicConfigStore'),
Ah, right. I guess `isConnected` and the `close` event are more about signalling that the provider is connected, and less about signalling that the provider itself is fully working. That's a good point. The way you've done it here is probably best then.

2019-11-21 23:40 UTC, Gudahtt commented on src/utils.js
> +  // there may be a simpler way of doing it, but this works
Interesting solution! This is missing a `.finally` though.

That could be added in the same way, but... I was wondering, did you try creating a real promise and attaching the `obj` properties to it instead? Sorta like the reverse of what you've done here. That should even hold up to `result instanceof Promise` checks, which would be nice.

2019-11-21 23:47 UTC, Gudahtt commented on index.js
> +      payload.jsonrpc = '2.0'
Cool! This will probably fix this issue: https://github.com/MetaMask/metamask-extension/issues/7433

2019-11-22 00:02 UTC, rekmarks commented on src/utils.js
> +  // there may be a simpler way of doing it, but this works
Good catch on the `.finally`.

I think you're highlighting the fundamental reason why we can't really have our cake and eat it too. If we can imagine someone doing `result instanceof Promise` and expecting it to be `true` - in the new usage of the method - we can also imagine someone expecting it to be `false` - in the old usage of the method.

I'm not sure what's best here.

2019-11-22 00:12 UTC, rekmarks commented on index.js
> +      payload.method === 'eth_accounts' ||
We'll have to review this in light of changes to `LoginPerSite`, but I don't think the inpage provider will ever be out of sync with the extension background. In other words, it'll call `_handleAccountsChanged`, but it ought to never do anything.

Nevertheless, if we ever break something such that it becomes out of sync, is it worth keeping as a defensive measure? It's a read-only method, sure, but we are in an async environment.

2019-11-22 00:14 UTC, Gudahtt commented on index.js
> +    sendSiteMetadata(this._rpcEngine)
This seems like an odd time to send site metadata - especially since it's called in a fire-and-forget way here, so the initial `requestAccounts` call might go through and trigger the connect notification before the metadata has arrived.

Would it be possible to move this to the constructor instead, after establishing a connection with MetaMask?

2019-11-22 00:17 UTC, rekmarks commented on index.js
> +    sendSiteMetadata(this._rpcEngine)
Yeah, moved it to the constructor.

2019-11-22 00:19 UTC, rekmarks commented
@Gudahtt, just pushed stuff, mostly related to things I marked resolved. Only significant changes worth looking over ought to be the `send` method. I kind of hate it, but it will remain something of a mess until we've stopped supporting the `send(requestObject, callback)` signature.

2019-11-22 00:20 UTC, Gudahtt commented on src/utils.js
> +  // there may be a simpler way of doing it, but this works
Fair point, but I had thought that by taking this "thenable" approach, we had already disregarded cases like that.

After all, even adding a `.then` will break a dapp that _does_ call `.then` but expects it to fail :smile:  But that's a fairly unreasonable expectation to have of this method, so I'm OK with breaking it.

Is there a case to be made for a consumer of the provider relying upon `result instanceof Promise` being `false`? I would hope that anybody checking whether the result is a Promise is then proceeding to handle the Promise (otherwise why bother check?). This might break dapps that _think_ they're supporting Promises correctly but aren't, but... I'm not sure that's on us.

2019-11-22 00:26 UTC, Gudahtt commented on src/utils.js
> +  // there may be a simpler way of doing it, but this works
Oh, also, we'll have to make sure `result.toString()` and `JSON.stringify(result)` return the same thing they did before too. Hmm.

Maybe your way is easier :sweat_smile:  This is just temporary after all - whatever's easiest to get working with `.then`, `.catch`, `.finally`, `toString`, and `JSON.stringify` is probably our best choice.

2019-11-22 00:40 UTC, Gudahtt commented on index.js
> +      payload.method === 'eth_accounts' ||
OK,  I'll take a look at the `LoginPerSite` branch later to look for these cases. It should be communicated by `wallet_accountsChanged` notifications I think?

If we ever _do_ end up relying upon this side-effect, it means something is already broken. Generally speaking I'd rather things blow up in production and us find out quickly, than them be subtly wrong in a way that takes longer for us to discover and fix. I don't feel that strongly about it though - feel free to leave it in as a backup if you want, I'm not going to block on it.

2019-11-22 01:20 UTC, rekmarks commented on index.js
> +      payload.method === 'eth_accounts' ||
How about this, inside `_handleAccountsChanged`?
```javascript
if (isEthAccounts) {
  log.warn(
    'MetaMask: Accounts may be out of sync. Please report this bug.',
    accounts,
  )
}
```

2019-11-22 01:22 UTC, rekmarks commented on src/utils.js
> +  // there may be a simpler way of doing it, but this works
Right! Good point about `toString` and `JSON.stringify`. I think Finlay may have raised that as a reason originally. We'll keep the current hack and hope for the best!

2019-11-22 01:46 UTC, Gudahtt commented on index.js
> + * @param {Array<any>} [params] - If given a method name, the method's parameters.
Nit: This should be updated to reflect that it can also be a Function - at least for now

2019-11-22 01:46 UTC, Gudahtt commented on index.js
> +    if ([
I think `!params` should be added to this condition? Synchronous send was only accessible if the second param was falsy

2019-11-22 01:46 UTC, Gudahtt commented on src/siteMetadata.js
> +  return window.location.hostname
Cool, this seems like a good fallback.

2019-11-22 01:46 UTC, Gudahtt commented on src/siteMetadata.js
> +function resourceExists (url) {
This is a great idea! 🙌

2019-11-22 01:46 UTC, Gudahtt commented on src/utils.js
> +      // legacy eth_accounts behavior
Interesting - where was this legacy behavior? I had trouble finding something that matched this.

2019-11-22 01:46 UTC, Gudahtt commented on test/utils.js
> +  Object.entries(customRes).forEach(async ([k, v1]) => {
I suspect that this might not complete before `t.end()` is called? As nothing is `await`-ing each of these loop operations.

You could update this to use an async iterator, or `await` in a for loop, or map the entries to `Promise.all` - one of those.

2019-11-22 01:46 UTC, Gudahtt commented on test/utils.js
> +      // } else if (v1 === target) {
Nit: leftover comment

2019-11-22 01:48 UTC, Gudahtt commented on index.js
> +      payload.method === 'eth_accounts' ||
Sure, that's a great idea! It could be challenging to detect these cases.

Though I take it that `isEthAccounts` would instead be a comparison between the results and `this._state.accounts`, or something along those lines.

2019-11-22 02:00 UTC, rekmarks commented on index.js
> +      payload.method === 'eth_accounts' ||
Cool! Yeah, I'm keep it in inside another if-block. I think we can put this one to bed!

2019-11-22 02:04 UTC, rekmarks commented on index.js
> + * @param {Array<any>} [params] - If given a method name, the method's parameters.
I'm not sure if it was documented originally, and I don't want to encourage anyone by indicating otherwise.

2019-11-22 02:04 UTC, Gudahtt commented on index.js
> +function getExperimentalApi (instance) {
It wasn't really even meant to be an "experimental" method in the first place - I just put it there because it was convenient 😬 

After giving this a bit more thought, I think I can accomplish what I set out to do with that `registerOnboarding` method in a simpler manner by adding a custom RPC method (e.g. `wallet_registerOnboarding`). I'll talk it over with some people tomorrow, but either way I think we should get these changes in first, and merge `one-click-onboarding` second.

2019-11-22 02:06 UTC, rekmarks commented on src/utils.js
> +      // legacy eth_accounts behavior
Ah, for a while on `LoginPerSite`, we were throwing EIP 1193 `unauthorized` errors in the background if the permission was not granted. We're always returning an array now, so I'm removing that clause.

2019-11-22 02:07 UTC, Gudahtt commented on index.js
> + * @param {Array<any>} [params] - If given a method name, the method's parameters.
It's still documented: https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.send(options%2C-callback)-(to-be-replaced)

2019-11-22 02:11 UTC, rekmarks commented on test/utils.js
> +  Object.entries(customRes).forEach(async ([k, v1]) => {
Hah, it was working before, but lord only knows why. I did a `.map` inside a `Promise.all` as I've been liking that pattern recently 💅

2019-11-22 02:13 UTC, rekmarks commented on index.js
> + * @param {Array<any>} [params] - If given a method name, the method's parameters.
Ah.

Can I still ignore it? 😅

2019-11-22 02:18 UTC, rekmarks commented on index.js
> -    if ('selectedAddress' in state && state.selectedAddress !== self.selectedAddress) {
Woah, I don't think we're cleaning up permissions when accounts are removed. If we do that, a notification should be produced.

Regarding switching and creating new accounts though, the account will only change from the dapp's perspective if the permission changes. I'm not sure exactly what we're doing with those in the UI, but I'll make sure to discuss it with @danjm.

2019-11-22 02:19 UTC, Gudahtt approved these changes
Phew 😌 , I think that's everything! This looks good to me. Both of the problems we encountered at the hackathon are fixed now (emitting `accountsChanged` upon unlock and accepting a callback to `.send`).

2019-11-22 02:24 UTC, Gudahtt commented on index.js
> -    if ('selectedAddress' in state && state.selectedAddress !== self.selectedAddress) {
Ah right, that's a good point. The site would need to explicitly be given permission to see the new account. We have that bulk assign permission screen, but it'd need to be revisited for each new account a user wanted to give access to.

Well, that makes it even simpler then, hopefully. I'll keep an eye out for this while looking over the extension `LoginPerSite` branch.

2019-11-22 16:46 UTC, Gudahtt commented on index.js
> +function getExperimentalApi (instance) {
Oh second thought, I'm going to merge `one-click-onboarding` since it's already gone through so many rounds of review and been approved. I also realized that it won't be possible to use an RPC message, as I need to grab the tab ID from the extension message API...

I'll just take care of the conflicts myself by putting up a separate PR to `LoginPerSite` (either this repo or the extension or both).

2019-11-22 17:17 UTC, rekmarks commented on index.js
> +function getExperimentalApi (instance) {
Thanks for letting me know. If that needs any integration with the new UI you should probably hold off on the PR until `LoginPerSite-ui` is merged into `LoginPerSite`. Just FYI!

2019-11-22 18:23 UTC, merged