fix: refactor to BaseProvider
MetaMask/providers pull request #144
Opened 2021-04-22 17:57 UTC by shanejonas

2021-04-23 04:25 UTC, rekmarks requested changes
Great addition with the tests!

I haven't reviewed them yet, because there's a fair amount in `BaseProvider` that should be moved to `MetaMaskInpageProvider`. `BaseProvider` should only include the non-deprecated events, properties, and methods defined in [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193).

2021-04-23 04:25 UTC, rekmarks commented on src/BaseProvider.ts
> +    };
All of these warnings and their associated events and properties should be moved to the `MetaMaskInpageProvider`.

I suppose we have add types such that subclasses can extended the state of `BaseProvider`.

2021-04-23 04:25 UTC, rekmarks commented on src/BaseProvider.ts
> +  public readonly _metamask: ReturnType<BaseProvider['_getExperimentalApi']>;
As these are not part of EIP-1193, I think all of them should be moved to `InpageProvider`. Even `isMetaMask` will not be relevant in all contexts.

The reason we've kept `_metamask` and its methods around is because of `_metamask.isUnlocked`, but it just struck, that's a trivial RPC method that we should implement.

2021-04-23 04:25 UTC, rekmarks commented on src/BaseProvider.ts
> +      shouldSendMetadata = true,
`shouldSendMetadata` and its functionality are specific to `InpageProvider` and should be moved there.

2021-04-23 04:25 UTC, rekmarks commented on src/BaseProvider.ts
> +    validateLoggerObject(logger);
This input validation is a pre-TypeScript hangover that we can probably take the opportunity to get rid of.

The only thing to keep would be `validateLoggerObject` if `ConsoleLike` isn't a good enough type.

2021-04-23 04:25 UTC, rekmarks commented on src/BaseProvider.ts
> +    }
I'd suggest we get rid of this input validation as well, but Node stream types can be extremely painful to work with, and this is a basically foolproof way to cause invalid streams at runtime.

2021-04-23 04:25 UTC, rekmarks commented on src/BaseProvider.ts
> +    mux.ignoreStream('phishing');
Should be moved to `InpageProvider`.

2021-04-23 04:25 UTC, rekmarks commented on src/BaseProvider.ts
> +    }
This should be moved to `InpageProvider`.

2021-04-23 04:25 UTC, rekmarks commented on src/BaseProvider.ts
> +    return new Proxy(
As part of the removal of the `_metamask` property, this should also be moved to `InpageProvider`.

2021-04-23 04:25 UTC, rekmarks commented on src/initializeProvider.ts
>  import { Duplex } from 'stream';
This file should probably be renamed `initializeInpageProvider`, because it assumes a browser environment.

2021-04-27 20:33 UTC, shanejonas commented on src/MetaMaskInpageProvider.ts
> +    // mux.ignoreStream('phishing');
dont have access to `mux` here, not sure where to put this

2021-04-27 20:34 UTC, shanejonas commented on src/MetaMaskInpageProvider.ts
> +    if (this.sentWarnings && this.sentWarnings.events[eventName as WarningEventName] === false) {
having this guard `this.sentWarnings &&` prevents this from running in the constructor, which is not ideal. but typescript initializes its default inherited properties after the base constructor runs

2021-04-28 13:24 UTC, Gudahtt commented on src/MetaMaskInpageProvider.ts
> +    // mux.ignoreStream('phishing');
Hmm. So this isn't needed for the inpage provider at all, because the phishing stream is intercepted by the concentscript. It doesn't get here at all.

But this interception doesn't happen with the extension provider :thinking: But maybe we can just... not send phishing events to other extensions specifically? We might be able to get by without this with an extension background change.

2021-04-28 15:23 UTC, rekmarks commented on src/MetaMaskInpageProvider.ts
> +    // mux.ignoreStream('phishing');
Yeah, this line has been unnecessary for a long time. We can just get rid of it!

2021-04-28 16:04 UTC, rekmarks requested changes
Looking good! Just a few more things to iron out.

2021-04-28 16:04 UTC, rekmarks commented on src/BaseProvider.ts
> +    }: BaseProviderOptions = {},
~Let's remove the default assignment to `{}` here since we're now expecting the consumers to always provide the appropriate arguments.~

2021-04-28 16:04 UTC, rekmarks commented on src/BaseProvider.ts
> +      // jsonRpcConnection.stream,
I don't believe that this should be commented.

2021-04-28 16:04 UTC, rekmarks commented on src/BaseProvider.ts
> +      // finally, after all state has be/.senen updated, emit the event
```suggestion
      // finally, after all state has been updated, emit the event
```

2021-04-28 16:04 UTC, rekmarks commented on src/MetaMaskInpageProvider.ts
>      const jsonRpcConnection = createStreamMiddleware();
Rather than calling `createStreamMiddleware` in the constructor of this class in addition to calling it in `BaseProvider`, we should make the `jsonRpcConnection` created in `BaseProvider` accessible to subclasses via a `protected` property.

2021-04-28 16:04 UTC, rekmarks commented on src/MetaMaskInpageProvider.ts
> +  protected sentWarnings: SentWarningsState = {
Since this property will be accessible to consumers, let's prefix it to encourage people not to mess with it:

```suggestion
  protected _sentWarnings: SentWarningsState = {
```

2021-04-28 16:04 UTC, rekmarks commented on src/MetaMaskInpageProvider.ts
> +    if (this.sentWarnings && this.sentWarnings.events[eventName as WarningEventName] === false) {
Huh, sure, why not!?

I take it we can accomplish the same thing with optional chaining?

```suggestion
    if (this?.sentWarnings.events[eventName as WarningEventName] === false) {
```

2021-04-28 18:37 UTC, shanejonas commented on src/BaseProvider.ts
> +    }: BaseProviderOptions = {},
i get some issues when i remove it:

```
● BaseProvider: RPC › ._rpcRequest › calls _handleAccountsChanged on request for eth_accounts

    TypeError: Cannot read property 'jsonRpcStreamName' of undefined

      110 |     connectionStream: typeof Duplex,
      111 |     {
    > 112 |       jsonRpcStreamName = 'metamask-provider',
          |       ^
      113 |       logger = console,
      114 |       maxEventListeners = 100,
      115 |     }: BaseProviderOptions,

      at new BaseProvider (src/BaseProvider.ts:112:7)
      at initializeProvider (test/BaseProvider.rpc.test.js:11:20)
      at Object.<anonymous> (test/BaseProvider.rpc.test.js:204:18)
      ```

2021-04-28 18:48 UTC, rekmarks commented on src/BaseProvider.ts
> +    }: BaseProviderOptions = {},
Oh, my bad. I mean to delete this suggestion after realizing it would probably cause issues 🤦

2021-04-28 19:54 UTC, rekmarks requested changes

2021-04-28 19:54 UTC, rekmarks commented on src/MetaMaskInpageProvider.ts
> -  }
I think this was correct. We should set `this.networkVersion` to `null` if the disconnection is non-recoverable.

2021-04-28 19:56 UTC, rekmarks commented on src/MetaMaskInpageProvider.ts
> -  }
I suppose it could be simplified to this:

```suggestion
  protected _handleDisconnect(isRecoverable: boolean, errorMessage?: string) {
    super._handleDisconnect(isRecoverable, errorMessage);
    if (this.networkVersion && !isRecoverable) {
      this.networkVersion = null;
    }
  }
```

2021-04-28 20:33 UTC, rekmarks commented on test/BaseProvider.rpc.test.js
> +const { BaseProvider } = require('../dist');
For posterity, the reason these tests worked with the `BaseProvider` streams set up incorrectly (see comment and changes [here](https://github.com/MetaMask/inpage-provider/pull/144#discussion_r622299174)) is because these tests mock `JsonRpcEngine.handle`, and we're not testing stream piping underlying that method at all.

2021-04-28 20:33 UTC, rekmarks approved these changes
LGTM!

2021-04-28 20:51 UTC, merged