feat: add createMetaMaskExternalExtensionProvider
MetaMask/providers pull request #152
Opened 2021-04-30 21:18 UTC by shanejonas

- remove index.d.ts

2021-04-30 21:29 UTC, shanejonas commented on src/createMetaMaskExternalExtensionProvider.ts
> +    ) as Runtime.Port;
I have to cast this to play nicely with the `webextension-polyfill-ts` type that `extension-port-stream` uses, doesnt seem to match exactly to what `chrome.runtime.connect` returns which is a `chrome.runtime.Port`

2021-05-03 18:29 UTC, rekmarks requested changes
Starting to look at this now. We should delete `index.d.ts` in a separate PR.

2021-05-03 20:20 UTC, rekmarks requested changes
Looks good! I have one request and one question:

Request: Since there are multiple of them, can we move all of the extension-related files into a new folder `src/extension-provider`?

Question: I'd like us to only use the `BaseProvider` instead of the inpage provider, to force consumers of this off the legacy API. What do you think of that?

2021-05-03 20:20 UTC, rekmarks commented on src/createMetaMaskExternalExtensionProvider.ts
> +    ) as Runtime.Port;
Makes sense. Port- and stream-related types seem to be incompatible 100% of the time.

2021-05-03 20:37 UTC, shanejonas commented
index.d.ts removal in this PR: https://github.com/MetaMask/inpage-provider/pull/153

2021-05-03 20:54 UTC, shanejonas commented
added `src/extension-provider`

2021-05-03 23:31 UTC, rekmarks approved these changes
LGTM!

2021-05-03 23:34 UTC, merged