Standardise repo per module template as of April 2023
MetaMask/providers pull request #254
Opened 2023-04-24 11:58 UTC by Mrtenz

Work in progress.

2023-04-24 15:56 UTC, Mrtenz commented on src/extension-provider/createExternalExtensionProvider.test.ts
> +      setTimeout(() =>
`setImmediate` is not available in recent versions of Node.js and/or browsers, so I've swapped this out to use `setTimeout`. For our purposes, it does effectively the same.

2023-04-24 15:57 UTC, Mrtenz commented on src/MetaMaskInpageProvider.ts
> +  // eslint-disable-next-line @typescript-eslint/promise-function-async
`send` can return a `Promise`, so ESLint wants to add `async` to it. This changes the behaviour of the function, however, as anything would make it return a `Promise`. To avoid this we have to suppress this rule here.

2023-04-24 17:27 UTC, FrederikBolding commented
Please document the breaking changes in this PR in the description.

2023-04-24 17:28 UTC, FrederikBolding requested changes

2023-04-24 17:28 UTC, FrederikBolding commented on tsconfig.json
> -  "include": ["./src/*.ts"],
Do we not need an `include`?

2023-04-24 17:28 UTC, FrederikBolding commented on .github/workflows/publish-release.yml
> +          npm-token: ${{ secrets.NPM_TOKEN }}
We shouldn't merge this until all tokens have been added to this repo

2023-04-24 17:28 UTC, FrederikBolding commented on src/extension-provider/createExternalExtensionProvider.test.ts
> +      describe(`${method}`, () => {
?

2023-04-24 17:28 UTC, FrederikBolding commented on src/siteMetadata.ts
> +  for (const icon of Array.from(icons)) {
Shouldn't this already be iterable?

2023-04-24 17:28 UTC, FrederikBolding commented on package.json
> +    "setup": "yarn install && yarn allow-scripts",
```suggestion
```

2023-04-24 17:28 UTC, FrederikBolding commented on package.json
> +    "prepublishOnly": "yarn build && yarn lint && yarn test",
```suggestion
```
I don't think this one is used anymore either?

2023-04-24 17:28 UTC, FrederikBolding commented on package.json
> +    "webextension-polyfill": "^0.10.0"
Why was this added? 🤔

2023-04-24 17:28 UTC, FrederikBolding commented on src/StreamProvider.ts
> -    this._handleStreamDisconnect = this._handleStreamDisconnect.bind(this);
Is this safe to remove because it is now hash private?

2023-04-24 17:28 UTC, FrederikBolding commented on src/MetaMaskInpageProvider.test.ts
> +            console.log('consoleWarnSpy.mock.calls', consoleWarnSpy.mock.calls);
```suggestion
```

2023-04-24 17:30 UTC, Mrtenz commented on src/siteMetadata.ts
> +  for (const icon of Array.from(icons)) {
Not according to TypeScript.

2023-04-24 17:31 UTC, Mrtenz commented on package.json
> +    "webextension-polyfill": "^0.10.0"
We import `Runtime` from it, so without, ESLint would complain.

2023-04-24 17:32 UTC, Mrtenz commented on src/StreamProvider.ts
> -    this._handleStreamDisconnect = this._handleStreamDisconnect.bind(this);
It's not used anywhere where it's not bound, so I think it's safe to remove. Otherwise we can't use a hash private function, as they are read-only.

2023-04-24 17:34 UTC, Mrtenz commented on tsconfig.json
> -  "include": ["./src/*.ts"],
Apparently not. It works like this, and is the same as the module template.

2023-04-24 17:45 UTC, FrederikBolding commented on package.json
> +    "webextension-polyfill": "^0.10.0"
Oh but we only use the type which is why it wasn't added before. Hmm 🤔

2023-04-24 17:47 UTC, FrederikBolding commented on src/siteMetadata.ts
> +  for (const icon of Array.from(icons)) {
Hmm, it is untested. So that is slightly worrying

2023-04-24 17:49 UTC, FrederikBolding commented on package.json
> +    "webextension-polyfill": "^0.10.0"
Not sure if we should ignore the eslint error or not

2023-04-24 17:49 UTC, FrederikBolding commented on package.json
> +    "webextension-polyfill": "^0.10.0"
I assume everything has been working until now

2023-04-24 17:49 UTC, FrederikBolding commented on src/StreamProvider.ts
> -    this._handleStreamDisconnect = this._handleStreamDisconnect.bind(this);
Note that it is a breaking change now that it cannot be accessed anymore

2023-04-24 17:50 UTC, FrederikBolding commented on src/siteMetadata.ts
> +  for (const icon of Array.from(icons)) {
Could we test it and make sure it doesn't break any existing logic?

2023-04-24 17:53 UTC, Mrtenz commented on src/siteMetadata.ts
> +  for (const icon of Array.from(icons)) {
`Array.from` just creates an array from the given value, so I doubt it would break anything? Testing in a browser locally, these two are equivalent:

```ts
const icons = document.querySelectorAll(...);
for (const icon of icons) { ... }
for (const icon of Array.from(icons)) { ... }
```

2023-04-24 17:54 UTC, Mrtenz commented on package.json
> +    "webextension-polyfill": "^0.10.0"
I don't think there's a downside to adding it?

2023-04-24 17:55 UTC, Mrtenz commented on src/StreamProvider.ts
> -    this._handleStreamDisconnect = this._handleStreamDisconnect.bind(this);
It's a private field, so I'm not sure if we need to consider this breaking. It's a change to the internal API.

2023-04-24 18:21 UTC, Gudahtt commented on .github/workflows/publish-release.yml
> +          npm-token: ${{ secrets.NPM_TOKEN }}
Tokens have been setup

2023-04-24 18:23 UTC, Gudahtt commented on package.json
> +    "node": ">=14.0.0"
It seems that npm has been updated to v16 but this is still on v14

2023-04-24 18:27 UTC, Gudahtt commented on package.json
> +    "node": ">=14.0.0"
The README still says v14 as well

2023-04-24 18:38 UTC, Mrtenz commented on package.json
> +    "node": ">=14.0.0"
Good catch! At least the engines part would be solved by MetaMask/metamask-module-template#191. 😄

2023-04-25 09:41 UTC, FrederikBolding commented on src/StreamProvider.ts
> -    this._handleStreamDisconnect = this._handleStreamDisconnect.bind(this);
Hmm, a lot of effort has been put into making `MetaMaskInpageProvider` non-breaking. Legacy functions etc, perhaps we shouldn't be changing the internal API for that? 

I wonder if some dapp exists that use the internal API because it is currently exposed

2023-04-25 09:54 UTC, FrederikBolding approved these changes

2023-04-26 11:02 UTC, merged