Add global initialization event
MetaMask/providers pull request #31
Opened 2020-04-14 00:27 UTC by rekmarks

aka `ethereum#initialized`

2020-04-17 22:00 UTC, Gudahtt requested changes
Could you move the version bump to a separate PR?

2020-04-17 22:03 UTC, rekmarks commented
@Gudahtt done

2020-04-17 22:07 UTC, Gudahtt submitted a review, later dismissed

2020-04-18 00:25 UTC, Gudahtt requested changes

2020-04-18 00:25 UTC, Gudahtt commented on src/MetamaskInpageProvider.js
> +    this.setMaxEventListeners(maxEventListeners)
I think this function is misnamed (https://nodejs.org/docs/latest-v10.x/api/events.html#events_emitter_setmaxlisteners_n)

```suggestion
    this.setMaxListeners(maxEventListeners)
```

2020-04-18 00:25 UTC, Gudahtt commented on src/initProvider.js
> +    provider = new Proxy(provider, proxyHandler)
Does this make sense as part of the provider API? 🤔 All this does is wrap it in a Proxy, which the caller could do more easily.

I'd suggest either removing it, or replace this with a flag to wrap it in a Proxy that prevents property deletion (e.g. the thing we use the Proxy for).

2020-04-18 17:10 UTC, rekmarks commented on src/initProvider.js
> +    provider = new Proxy(provider, proxyHandler)
I added a default proxy handler that's the same as the one in the extension's `inpage.js`.

The benefit of handling the Proxy here is that we can update it in one place and use it in both mobile and the extension.

2020-04-20 17:49 UTC, Gudahtt commented on src/initProvider.js
> +    provider = new Proxy(provider, proxyHandler)
This API still seems.... very strange? As a consumer of this package, why would I want to pass in a `proxyHandler`? What utility would it have? What would the consequences be of passing in a `proxyHandler` (i.e. it'd break compatibility with older version of `web3`, but that's not easy to tell from looking at this API).

A flag called `web3Compatibility` or `preventPropertyDeletion` or something like that might make it more clear what's going on (defaulting to `true`). Then the consumer could disable it and handle the proxy wrapping by themselves, or they could leave it enabled and create their own proxy... whichever. It would at least be clearer then _what_ we're doing and _why_.

2020-04-20 18:17 UTC, rekmarks commented on src/initProvider.js
> +    provider = new Proxy(provider, proxyHandler)
I did `preventPropertyDeletion`

2020-04-20 18:22 UTC, Gudahtt approved these changes
LGTM!

2020-04-20 18:23 UTC, merged