Enable package consumers to specify a logger
MetaMask/providers pull request #88
Opened 2020-07-30 16:21 UTC by rekmarks

- Add named param `logger` to constructor
  - This object is assigned to a global variable `log`, which is used in place of `console` for all logging calls
  - By default, `logger = console`

2020-07-30 16:22 UTC, rekmarks commented on src/MetamaskInpageProvider.js
> +let log
Global because we don't want websites to mess with it.

2020-07-30 19:08 UTC, brad-decker requested changes

2020-07-30 19:08 UTC, brad-decker commented on src/MetamaskInpageProvider.js
> +    log = logger
[?]: Shouldn't we do some checking on the provided logger to make sure that it has the expected methods and signatures?

2020-08-04 16:06 UTC, Gudahtt commented on src/MetamaskInpageProvider.js
> +    log = logger
Or alternatively, specify the type of the `opts.logger` parameter more precisely than `Object`?

It seems fair to expect consumers to pass in valid parameters if they're typed adequately, but it's not at the moment.

2020-08-04 16:10 UTC, rekmarks commented on src/MetamaskInpageProvider.js
> +    log = logger
I added validation here: 98298c1

How do we feel about the required methods?

2020-08-04 16:11 UTC, rekmarks commented on src/MetamaskInpageProvider.js
> +    log = logger
I'll improve the type, too.

2020-08-04 16:17 UTC, rekmarks commented on src/MetamaskInpageProvider.js
> +    log = logger
`typedef` added in f68e8c3

2020-08-04 16:35 UTC, rekmarks commented
`log` and `debug` are aliases in `loglevel`. Should we just require one or the other?
https://npmjs.com/package/loglevel

2020-08-04 16:46 UTC, brad-decker approved these changes
Changes LGTM 👍

2020-08-04 16:48 UTC, brad-decker commented
We could either manually alias them if one is provided or not the other, or validate that one exists, but if we use one and the other is provided then we have an issue. Technically we only need to validate that the methods used in the library are provided

2020-08-04 16:56 UTC, Gudahtt commented
I would consider `console` to be the API to emulate here, not `loglevel`. But I don't think it's important to validate the existence of any methods we don't actually use.

2020-08-04 16:59 UTC, merged

2020-08-04 17:01 UTC, rekmarks commented
Fair points, although I decided to keep the properties (which in my mind are the most commonly used) in case we decide to use any of them in the future.