Create index.d.ts
MetaMask/providers pull request #92
Opened 2020-08-15 07:27 UTC by Jack-Works

2020-08-15 16:45 UTC, rekmarks commented
Thanks for making this, @Jack-Works! We've started to implement some types for this internally, but never finished the job. We'll be reviewing this in the coming days 👍

2020-08-16 07:23 UTC, danfinlay submitted a review, later dismissed
Overall a great addition, but we should do it without license changes.

2020-08-16 07:23 UTC, danfinlay commented on index.d.ts
> +import { AbstractProvider } from 'web3-core';
I see web3-core is LGPL, which could taint the license of our whole project, so we might want to just write this fairly simple part under an even more permissive license.

2020-08-16 11:08 UTC, Jack-Works commented on index.d.ts
> +import { AbstractProvider } from 'web3-core';
AbstractProvider is a simple interface I can add it without add web3-core as a dependency. I will do the change later

2020-08-16 19:22 UTC, rekmarks commented
@Jack-Works for your reference, @brad-decker (on our team) previously sketched the following types for this package. I'm not suggesting you have to adapt any of this over what you've done, but in case it's useful: https://gist.github.com/rekmarks/1d249cb9d805f8b8ad89467ae961517b

2020-08-16 19:23 UTC, rekmarks commented on index.d.ts
> +    get publicConfigStore(): any;
We're planning to remove the `publicConfigStore` property, so I'm not sure if we should include it or not 🤔

2020-08-16 19:28 UTC, rekmarks commented on index.d.ts
> +    readonly chainId: undefined;
They should be `string | null`

ref: #93

2020-08-16 19:29 UTC, rekmarks commented on index.d.ts
> +    logger?: Console;
Could we extend this to allow other loggers? For reference, we should probably turn this into a type: https://github.com/MetaMask/inpage-provider/blob/master/src/MetamaskInpageProvider.js/#L696

2020-08-16 19:31 UTC, rekmarks commented on index.d.ts
> +    request(jsonRPCPayload: object): Promise<unknown>;
`request` should follow the `RequestArguments` type defined in EIP-1193: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#request

I also think it's in `web3-core`.

2020-08-16 19:32 UTC, rekmarks commented on index.d.ts
> +    sendAsync(jsonRPCPayload: object, callback: (err: Error | undefined, result: undefined) => void): void;
The `jsonRPCPayload` should be typed like it is in `web3-core`.

2020-08-17 16:25 UTC, rekmarks commented on index.d.ts
> +    id: number
```suggestion
    id: string | number
```

2020-08-17 16:26 UTC, rekmarks commented on index.d.ts
> +    params: unknown[]
`params` are not always required.
```suggestion
    params?: unknown[]
```

2020-08-17 16:33 UTC, rekmarks commented on index.d.ts
> +    error?: string
All errors follow this type, without the `stack`: https://github.com/MetaMask/eth-rpc-errors/blob/master/%40types/index.d.ts#L2-L7

2020-08-18 17:24 UTC, brad-decker submitted a review, later dismissed
LGTM, good work!

2020-08-18 17:52 UTC, rekmarks commented on index.d.ts
> +        stack?: any
Last bit of feedback, the `stack` will never be present here in practice:
```suggestion
```

2020-08-18 17:53 UTC, rekmarks commented on index.d.ts
> +    request(args: JsonRpcPayload): Promise<any>
We should prefer `unknown`:
```suggestion
    request(args: JsonRpcPayload): Promise<unknown>
```

2020-08-18 17:54 UTC, rekmarks requested changes
Just a couple more pieces of minor changes, then we should be good to go!

2020-08-19 03:40 UTC, rekmarks approved these changes
LGTM!

Great work @Jack-Works. Many thanks!

2020-08-19 03:43 UTC, merged